.TH GradeMan2 "1" "2.0.0" "class management for teachers"

.SH NAME
GradeMan2 \- class management database for teachers.
Since 

.SH SYNOPSIS
\fBGradeMan2\fR\fR

.SH DESCRIPTION
GradeMan2 manages your student grades and your entire class organization.

.SH OPTIONS
.IP "\f[none]\fR" 4
There are no command line options, since GradeMan2 is a GUI software

.SH HOMEPAGE
More information about GradeMan2 can be found at <\fIhttps://polarwinkel.de/grademan.html\fR>.

.SH AUTHOR
GradeMan was written by Dirk Winkel <\fIit@polarwinkel.de\fR>.
